package handoff

import (
	"bytes"
	"fmt"
	"strings"
	"text/template"
	"time"

	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
)

// templateData is the structured view of a HandoffContext used by the Go template.
type templateData struct {
	// Project
	Repo        string
	ConceptName string
	Phase       string
	Tier        string
	RawConcept  string

	// Planning artifacts
	Artifacts    map[string]string
	PlanningPRURL string
	EpicCount    int64
	FeatureCount int64
	IssueCount   int64
	ROAM         string

	// Sprint / feature / task / worker summaries
	Sprints  []sprintRow
	Features []featureRow
	Tasks    []taskRow
	Workers  []workerRow
}

type sprintRow  struct{ Name, Type, Phase string }
type featureRow struct{ Name, Phase string }
type taskRow    struct{ Name, Worker, Priority, Phase string; PRNumber int64 }
type workerRow  struct{ Name, AgentType, Phase string }

const handoffTemplate = `
⚠️ COO HANDOFF WORKSPACE — READ THIS SECTION FIRST
====================================================

This workspace is managed by **itsacoo** (Code Orchestrator Operator), a
Kubernetes-native AI software development system.  The operator manages the
full lifecycle of concepts from planning through execution using a hierarchy of
custom resources: COOConcept → COOPlan → COOSprints → COOFeatures → COOTasks.

## Project

| Field       | Value                |
|-------------|----------------------|
| Repo        | {{ .Repo }}          |
| Concept     | {{ .ConceptName }}   |
| Phase       | {{ .Phase }}         |
| Complexity  | {{ .Tier }}          |

### Original Requirement

{{ .RawConcept }}

## Planning Artifacts

| Artifact | Path / URL |
|----------|-----------|
{{- range $k, $v := .Artifacts }}
| {{ $k }} | {{ $v }} |
{{- end }}

{{- if .PlanningPRURL }}

Planning PR: {{ .PlanningPRURL }}
{{- end }}
{{- if or .EpicCount .FeatureCount .IssueCount }}

Counts — Epics: {{ .EpicCount }} | Features: {{ .FeatureCount }} | Issues: {{ .IssueCount }}
{{- end }}
{{- if .ROAM }}

ROAM: {{ .ROAM }}
{{- end }}

## Sprint Summary

{{- if .Sprints }}
| Sprint | Type | Phase |
|--------|------|-------|
{{- range .Sprints }}
| {{ .Name }} | {{ .Type }} | {{ .Phase }} |
{{- end }}
{{- else }}
_No sprints found._
{{- end }}

## Features

{{- if .Features }}
| Feature | Phase |
|---------|-------|
{{- range .Features }}
| {{ .Name }} | {{ .Phase }} |
{{- end }}
{{- else }}
_No features found._
{{- end }}

## Tasks

{{- if .Tasks }}
| Task | Worker | Priority | Phase | PR |
|------|--------|----------|-------|----|
{{- range .Tasks }}
| {{ taskStatus .Phase }} {{ .Name }} | {{ .Worker }} | {{ .Priority }} | {{ .Phase }} | {{ prLink .PRNumber }} |
{{- end }}
{{- else }}
_No tasks found._
{{- end }}

## Worker Roster

{{- if .Workers }}
| Worker | Agent Type | Phase |
|--------|-----------|-------|
{{- range .Workers }}
| {{ .Name }} | {{ .AgentType }} | {{ .Phase }} |
{{- end }}
{{- else }}
_No workers found._
{{- end }}

## What You Should Do

{{- if eq .Phase "Planned" }}

1. Review the planning PR (link above) for PRD/HLD/LLD/epic/tasks.
2. Check the generated GitHub issues for correctness.
3. Approve the planning PR to trigger Sprint 1 execution.
{{- else if eq .Phase "Executing" }}

1. Review the task list above — pick up any ⏳ open tasks.
2. Review worker PRs and provide feedback where needed.
3. Mark tasks done in the operator by closing the relevant GitHub issues.
{{- else }}

1. Check the Phase field above and refer to itsacoo operator documentation for
   guidance on the next steps for this concept phase.
{{- end }}

---
_Generated by coo-cli at {{ .GeneratedAt }}_
`

// templateFuncs are helpers available inside the template.
var templateFuncs = template.FuncMap{
	"taskStatus": func(phase string) string {
		if strings.EqualFold(phase, "completed") || strings.EqualFold(phase, "done") {
			return "✅"
		}
		return "⏳"
	},
	"prLink": func(prNumber int64) string {
		if prNumber == 0 {
			return "-"
		}
		return fmt.Sprintf("#%d", prNumber)
	},
}

// templateDataWithTime extends templateData with a generated timestamp field
// accessible in the template.
type templateDataWithTime struct {
	templateData
	GeneratedAt string
}

// RenderTemplate converts a HandoffContext into a CLAUDE.md header string.
func RenderTemplate(hc *HandoffContext) (string, error) {
	td := buildTemplateData(hc)

	tmpl, err := template.New("handoff").Funcs(templateFuncs).Parse(handoffTemplate)
	if err != nil {
		return "", fmt.Errorf("parse handoff template: %w", err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, templateDataWithTime{
		templateData: td,
		GeneratedAt:  time.Now().UTC().Format(time.RFC3339),
	}); err != nil {
		return "", fmt.Errorf("execute handoff template: %w", err)
	}

	return buf.String(), nil
}

// buildTemplateData converts a HandoffContext into a templateData struct.
func buildTemplateData(hc *HandoffContext) templateData {
	td := templateData{
		Artifacts: map[string]string{},
	}

	if hc.Concept != nil {
		td.ConceptName = hc.Concept.GetName()

		// spec fields
		td.RawConcept, _, _ = unstructured.NestedString(hc.Concept.Object, "spec", "rawConcept")
		td.Phase, _, _ = unstructured.NestedString(hc.Concept.Object, "status", "phase")
		td.Tier, _, _ = unstructured.NestedString(hc.Concept.Object, "status", "complexityAssessment", "tier")

		// Derive repo from affectedProjects[0] if available.
		projects, _, _ := unstructured.NestedStringSlice(hc.Concept.Object, "spec", "affectedProjects")
		if len(projects) > 0 {
			td.Repo = projects[0]
		}
	}

	if hc.Plan != nil {
		// Artifacts map: keys are artifact type names, values are paths/URLs.
		artifacts, found, _ := unstructured.NestedMap(hc.Plan.Object, "spec", "artifacts")
		if found {
			for k, v := range artifacts {
				if s, ok := v.(string); ok {
					td.Artifacts[k] = s
				}
			}
		}

		td.PlanningPRURL, _, _ = unstructured.NestedString(hc.Plan.Object, "status", "planningPRURL")

		epicCount, _, _ := unstructured.NestedInt64(hc.Plan.Object, "status", "epicCount")
		td.EpicCount = epicCount

		featureCount, _, _ := unstructured.NestedInt64(hc.Plan.Object, "status", "featureCount")
		td.FeatureCount = featureCount

		issueCount, _, _ := unstructured.NestedInt64(hc.Plan.Object, "status", "issueCount")
		td.IssueCount = issueCount

		td.ROAM, _, _ = unstructured.NestedString(hc.Plan.Object, "status", "roam")
	}

	for _, s := range hc.Sprints {
		sprintType, _, _ := unstructured.NestedString(s.Object, "spec", "type")
		phase, _, _ := unstructured.NestedString(s.Object, "status", "phase")
		td.Sprints = append(td.Sprints, sprintRow{
			Name:  s.GetName(),
			Type:  sprintType,
			Phase: phase,
		})
	}

	for _, f := range hc.Features {
		phase, _, _ := unstructured.NestedString(f.Object, "status", "phase")
		td.Features = append(td.Features, featureRow{
			Name:  f.GetName(),
			Phase: phase,
		})
	}

	for _, t := range hc.Tasks {
		worker, _, _ := unstructured.NestedString(t.Object, "spec", "worker")
		priority, _, _ := unstructured.NestedString(t.Object, "spec", "priority")
		phase, _, _ := unstructured.NestedString(t.Object, "status", "phase")
		prNumber, _, _ := unstructured.NestedInt64(t.Object, "status", "prNumber")
		td.Tasks = append(td.Tasks, taskRow{
			Name:     t.GetName(),
			Worker:   worker,
			Priority: priority,
			Phase:    phase,
			PRNumber: prNumber,
		})
	}

	for _, w := range hc.Workers {
		agentType, _, _ := unstructured.NestedString(w.Object, "spec", "agentType")
		phase, _, _ := unstructured.NestedString(w.Object, "status", "phase")
		td.Workers = append(td.Workers, workerRow{
			Name:      w.GetName(),
			AgentType: agentType,
			Phase:     phase,
		})
	}

	return td
}
